### ISSUE TITLE
Couldn't get available versions for package mageplaza/magento-2-korean-language-pack

### ISSUE THREAD

**Issue by vecanc** [mageplaza/magento-2-korean-language-pack#3]
when doing system upgrade, got the following error.  How to resovle?
Couldn't get available versions for package mageplaza/magento-2-korean-language-pack

**Comment by imsamthomas** [comment]
Hi @vecanc,

You should run the following command line to install:

```
composer require mageplaza/magento-2-korean-language-pack:dev-master
```

**Comment by vecanc** [comment]
I have no issue to install.  I do this way:

composer require mageplaza/magento-2-korean-language-pack:*@dev


However, I only get error when I upgrade.


What can we do?


Thks


________________________________

**Comment by imsamthomas** [comment]
Hi,

Can you pleas paste the error here?

**Comment by zebeel** [comment]
Close due to no response in 7 days
